<title>BTC Battles - Rounder Checker</title>
<?php
 include 'settings.php';
?>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script>
    var STEAMID = '<?php echo $user['steamid']; ?>';
    var TRADELINK = '<?php echo $user['tradelink']; ?>';
  </script>

  <script src="assets/js/jquery-3.2.1.js"></script>
  <script src="assets/js/jquery.cookie.js"></script>
  <script src="assets/js/jquery.dataTables.min.js"></script>
  <script src="assets/js/socket.io-1.4.5.js"></script>
  <script src="assets/js/cryptojs.js"></script>
  <script src="assets/js/notify.js"></script>
  <script src="assets/js/tinysort.js"></script>

  <script src="assets/js/countdownHackerTimer.js"></script>
  <script src="assets/js/countTo.js"></script>

  <script>
    $.notify.defaults({
      clickToHide: true,
      autoHide: true,
      autoHideDelay: 2000,
      arrowShow: true,
      arrowSize: 177,
      position: 'top center',
      elementPosition: 'top center',
      globalPosition: 'top center',
      style: 'bootstrap',
      className: 'error',
      showAnimation: 'slideToggle',
      showDuration: 600,
      hideAnimation: 'slideToggle',
      hideDuration: 600,
      gap: 2
    });
  </script>
  <link rel="stylesheet" type="text/css" href="assets/css/app.css?v=<?=time()?>">
  <link rel="stylesheet" type="text/css" href="assets/css/font-awesome.min.css?v=<?=time()?>">
  <link rel="stylesheet" type="text/css" href="assets/css/animate.min.css?v=<?=time()?>">
  <link rel="stylesheet" type="text/css" href="assets/css/bootstrap.css?v=<?=time()?>">
  <link rel="stylesheet" type="text/css" href="assets/css/w3.css?v=<?=time()?>">
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/themify-icons/0.1.2/css/themify-icons.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">
</head>

  <?php include 'preheader.php'; ?>
<nav class="navbar navbar-inverse">
    <div class="logo">
        <a href="/">
            <img src="assets/images/logo-72dpi.png" srcset="assets/images/logo-retina.png 2x" alt="Logo">
        </a>
    </div>
    <div class="">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">

            <ul class="nav navbar-nav menu header-menu">
                <?php include 'Header.php'; ?>
            </ul>

            <ul class="nav navbar-nav navbar-right header-menu">
                <li>
                    <?php
                    if ($user) {
                        echo '';
                    } else {
                        echo '<button id="openLogin" class="btn duel-btn-lg btn-create btn-lg btn-block">LOGIN</button> <button id="openRegister" class="btn duel-btn-lg btn-create btn-lg btn-block">REGISTER</button>';
                    }
                    ?>
                </li>

            </ul>
        </div>
    </div>
</nav>
<body class="hellos">



<div class="container fair-container" style="width: 1170px;">

    <div class="starter-template starter-template fair-inner-container" style="text-align:left;">

        <h3 class="fair-header fair-main-header">Selecting the winner:</h3>

      <p>
        The round secret is generated at the beginning of the round but only shown at the end, and it's meant to encrpyt the winner percentage and allow you to verify the winning ticket via the round identifier.<br>
    The round hash is an md5 string that is given at the beginning of the round, it is generated by joining the round secret with the winner percentage, separated by a "-", so a round hash is an md5 encrypted string of [roundSecret]-[winningPercentage]</p>
      <p>Here is how the winner ticket is counted</p>
      <p class="alert alert-info">CryptoJS.AES.decrypt(codeCrypted, hash+secret).toString(CryptoJS.enc.Utf8);</p>

        <h3 class="fair-header">Round Hash:</h3>

      <p style="font-size:14px;">The hash is an AES encryption of percentage.
      When the round is over, the secret is revealed.<br>You can verify that the hash matches with them with filling correctly the form below.</p>

        <h3 class="fair-header">Round hash verify:</h3>
      <p style="font-size:14px;">You can verify each round here. If the parameters are correct, it displays the winner number of the round.</p>
      <div class="panel panel-default" style="background: #1d1d1d;border-radius: 3px;">
        <div class="panel-body">
          <form action="" method="post" id="form" class="form-horizontal">
          <div class="form-group">
            <div class="col-sm-2 control-label">
              <label for="hash">Hash:</label>
            </div>
            <div class="col-sm-10">
              <input name="hash" class="form-control" id="hash" value="<?php echo $_GET['hash']; ?>" style="background: rgba(45, 45, 45, 0.7);border-color: rgba(45, 45, 45, 0.7);border-radius: 2px;color: rgba(173, 173, 173, 0.9);font-weight: 600;font-size: 13px;font-family: 'Open Sans', sans-serif;letter-spacing: 0.5px;">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label">
              <label for="secret">Secret:</label>
            </div>
            <div class="col-sm-10">
              <input name="secret" class="form-control" id="secret" value="<?php echo $_GET['secret'];?>" style="background: rgba(45, 45, 45, 0.7);border-color: rgba(45, 45, 45, 0.7);border-radius: 2px;color: rgba(173, 173, 173, 0.9);font-weight: 600;font-size: 13px;font-family: 'Open Sans', sans-serif;letter-spacing: 0.5px;">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label">
              <label for="tickets">Tickets:</label>
            </div>
            <?php echo " ";?>
            <div class="col-sm-10">
              <input name="tickets" class="form-control" id="tickets" value="<?php echo $_GET['tickets']; ?>" style="background: rgba(45, 45, 45, 0.7);border-color: rgba(45, 45, 45, 0.7);border-radius: 2px;color: rgba(173, 173, 173, 0.9);font-weight: 600;font-size: 13px;font-family: 'Open Sans', sans-serif;letter-spacing: 0.5px;">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-2 control-label"></div>
            <div class="col-sm-10"><button type="button" name="form" id="findWinningTicket" class="new__game__button">Check</button></div>
          </div>
          </form>
        </div>
      </div>

    </div>

  </div>


<script>
$('#findWinningTicket').click(function() {
  console.log("A");
  var hash = $('#hash').val();
  var secret = $('#secret').val();
  var tickets = $('#tickets').val();

   if(hash && secret) {
    $.ajax({
     url:"/getWinner.php?hash="+hash+"&secret="+secret+"&tickets="+tickets,
     success:function(data){
      try{
       data = JSON.parse(data);
       if(data.success){

        console.log(data);
          var winnerCorrect = CryptoJS.AES.decrypt(data.cryptedData, hash.concat(secret)).toString(CryptoJS.enc.Utf8);

          if(winnerCorrect == data.winner)
          {
            $.notify('Game verification successful, the winner was player' + data.winner, 'success');
          }
          else
          {
            $.notify('This round is not corrected', 'success');
          }
        }else{
         $.notify(data.error, 'success');
       }
      }catch(err){
        $.notify(err, 'success');
      }
     },
     error:function(err){
        $.notify(err, 'success');
     }
    });
   } else {
    $.notify('Error: Complete all fields', 'success');
   }

});
</script>


<!-- ALLL MODALS -->
<?php include 'Modals.php'; ?>
<!-- ALL MODALS -->



</body>
